# Generated by Django 2.2 on 2019-04-06 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('penalty', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('rank', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('.none', 'NOT_SELECTED'), ('.py', 'PYTHON'), ('.c', 'C'), ('.cpp', 'CPP')], default='.none', max_length=5)),
                ('submission_file', models.FileField(upload_to='content/submissions/submission_140109ba47654103b2ddd6d5b61ad285<django.db.models.fields.CharField>')),
                ('timestamp', models.DateTimeField()),
                ('judge_score', models.PositiveSmallIntegerField(default=0)),
                ('ta_score', models.PositiveSmallIntegerField(default=0)),
                ('final_score', models.FloatField(default=0.0)),
                ('linter_score', models.FloatField(default=0.0)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Person')),
            ],
        ),
        migrations.RemoveField(
            model_name='problem',
            name='id',
        ),
        migrations.AddField(
            model_name='problem',
            name='code',
            field=models.CharField(default='UNSET', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='file_format',
            field=models.CharField(default='.py,.cpp,.c', max_length=100),
        ),
        migrations.AddField(
            model_name='problem',
            name='input_format',
            field=models.CharField(default='No input format specified. Figure it out yourself Sherlock!', max_length=1000),
        ),
        migrations.AddField(
            model_name='problem',
            name='memory_limit',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='problem',
            name='name',
            field=models.CharField(default='Name not set', max_length=50),
        ),
        migrations.AddField(
            model_name='problem',
            name='output_format',
            field=models.CharField(default='No output format specified. Figure it out yourself Sherlock!', max_length=500),
        ),
        migrations.AlterField(
            model_name='problem',
            name='statement',
            field=models.TextField(default='The problem statement is empty. Good luck solving it!', max_length=2500),
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('public', models.BooleanField()),
                ('testcase_id', models.CharField(default='980f2630c3ce4ce4820ba3fea19cdd4e', max_length=128, primary_key=True, serialize=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionTestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('P', 'Pass'), ('F', 'Fail'), ('TE', 'TLE'), ('ME', 'OOM'), ('CE', 'COMPILATION_ERROR'), ('RE', 'RUNTIME_ERROR'), ('NA', 'NOT_AVAILABLE')], default='NA', max_length=2)),
                ('memory_taken', models.PositiveIntegerField()),
                ('time_taken', models.DurationField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Submission')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.TestCase')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Problem'),
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='ContestPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.BooleanField()),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Contest')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Person')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Problem')),
            ],
        ),
    ]
