# Generated by Django 2.2 on 2019-04-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_auto_20190406_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='start_code',
            field=models.FileField(null=True, upload_to='content/<django.db.models.fields.CharField>/start_code.zip'),
        ),
        migrations.AddField(
            model_name='problem',
            name='time_limit',
            field=models.DurationField(default=200),
        ),
        migrations.AlterField(
            model_name='problem',
            name='memory_limit',
            field=models.PositiveIntegerField(default=200000),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_file',
            field=models.FileField(upload_to='content/submissions/submission_39e0bf1fe31a4dc8afe184fbb31d534b<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='testcase_id',
            field=models.CharField(default='48a5f2e4f1b14836815e4b9575847ca0', max_length=128, primary_key=True, serialize=False),
        ),
    ]
