# Generated by Django 2.2 on 2019-04-06 18:05

from django.db import migrations, models
import judge.models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_auto_20190406_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='max_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='setter_solution',
            field=models.FileField(null=True, upload_to=judge.models.setter_sol_name),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_file',
            field=models.FileField(upload_to='content/submissions/submission_3359922f695147b5b27a440358b98235<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='testcase_id',
            field=models.CharField(default='fb7f44c4615a42318a2e3f2ff9387968', max_length=128, primary_key=True, serialize=False),
        ),
    ]
