# Generated by Django 2.2 on 2019-04-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_auto_20190406_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='comp_script',
            field=models.FileField(default='./default/default_compilation_script.sh', upload_to='content/<django.db.models.fields.CharField>/comp_script.sh'),
        ),
        migrations.AddField(
            model_name='problem',
            name='test_script',
            field=models.FileField(default='./default/default_test_script.sh', upload_to='content/<django.db.models.fields.CharField>/test_script.sh'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_file',
            field=models.FileField(upload_to='content/submissions/submission_a64b1b2d3bc44b7abdf5c3ab1f074f8d<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='testcase_id',
            field=models.CharField(default='ad0739aa64c84408aa880b7974f76bb1', max_length=128, primary_key=True, serialize=False),
        ),
    ]
