# Generated by Django 2.2 on 2019-04-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_auto_20190406_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.FileField(default='./default/default_comment.yml', upload_to='content/comment/2564670c99934ed78cb5eecbe76965fd.yml'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.CharField(default='2564670c99934ed78cb5eecbe76965fd', max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='testcase',
            name='inputfile',
            field=models.FileField(default='./default/default_inputfile.yml', upload_to='content/testcase/inputfile_45ccbee1427f440b8e3adfda5353f71c.txt'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='outputfile',
            field=models.FileField(default='./default/default_outputfile.yml', upload_to='content/testcase/outputfile_45ccbee1427f440b8e3adfda5353f71c.txt'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_file',
            field=models.FileField(upload_to='content/submissions/submission_53636f9dcbb24123ba2541a825275518<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='testcase_id',
            field=models.CharField(default='45ccbee1427f440b8e3adfda5353f71c', max_length=128, primary_key=True, serialize=False),
        ),
    ]
